# Form implementation generated from reading ui file 'RadioButton.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 291, 271))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.radioButton = QtWidgets.QRadioButton(parent=self.widget)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton.clicked.connect(self.on_radioButton_clicked)
        self.verticalLayout.addWidget(self.radioButton)

        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.widget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_3.toggled.connect(self.on_radioButton_clicked)
        self.verticalLayout.addWidget(self.radioButton_3)

        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.widget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_2.toggled.connect(self.on_radioButton_clicked)
        self.verticalLayout.addWidget(self.radioButton_2)

        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.widget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_4.toggled.connect(self.on_radioButton_clicked)
        self.verticalLayout.addWidget(self.radioButton_4)
        
        
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def on_radioButton_clicked(self):
        sender = self.sender()
        self.label_2.setText(f"You selected: {sender.text()}")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Flight Type"))
        self.label.setText(_translate("Form", "Select the Flight Type:"))
        self.radioButton.setText(_translate("Form", "Option 1"))
        self.radioButton_3.setText(_translate("Form", "Option 2"))
        self.radioButton_2.setText(_translate("Form", "Option 3"))
        self.radioButton_4.setText(_translate("Form", "Option 4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
